"""empty message

Revision ID: 15a1470d6de9
Revises: 047f05bb5c4b
Create Date: 2023-10-15 08:17:17.841816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a1470d6de9'
down_revision = '047f05bb5c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('diagnoses', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('white_blood_cells', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('birthday')

    with op.batch_alter_table('patient_update', schema=None) as batch_op:
        batch_op.drop_column('white_blood_cells')
        batch_op.drop_column('diagnoses')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
