"""added pain points

Revision ID: 8a66b4181852
Revises: 5b27dd0924cd
Create Date: 2023-10-14 21:31:05.455864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a66b4181852'
down_revision = '5b27dd0924cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pain_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('patient_update_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_update_id'], ['patient_update.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pain_point')
    # ### end Alembic commands ###
